services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  app:
    build: .
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      REDIS_URL: "redis://redis:6379/0"
      CACHE_TTL: "300"
      AVIATIONSTACK_BASE_URL: "http://api.aviationstack.com/v1"
      OPENWEATHER_BASE_URL: "https://api.open-meteo.com/v1"
      DEFAULT_WEATHER_CITY: "Frankfurt"
      OPENWEATHER_LAT: "50.1109"
      OPENWEATHER_LON: "8.6821"
      AVIATIONSTACK_API_KEY: "${AVIATIONSTACK_API_KEY}"
      OPENWEATHER_API_KEY: "${OPENWEATHER_API_KEY}"
